### ISSUE TITLE
Add I18N

### ISSUE THREAD

**Issue by supernoir** [supernoir/wikivent#3]

**Comment by 839083** [comment]
Sorry, was away for several weeks due to final exams and moving apartments. Are we still planning to continue this project?

**Comment by supernoir** [comment]
Hi @839083, it was the same for me (more stuff to do at work). I would love to. I just didn't find the time so far. Are you interested in continuing? If so we can definitely figure out what else needs doing. There's still a lot to be done :) Thanks for getting in touch in any event!

**Comment by 839083** [comment]
Sure, just wanted to check! I'm now free all summer because of COVID

**Comment by supernoir** [comment]
I see... Great to have you on board then!
Here are some of the things I know need to be done first:

- Fix filtering / sorting on the main ventilator table
- Rewrite components with the the help of Grommet (Responsiveness)
- Solve issue with re-render when using Rest Hooks
- Wrap "Article-type" pages (About, etc) in their own component for reuse
- Clean up Issues
- Write content for Article pages (=> translate as next step)
- Fix Language Switcher select
- Add more ventilator categories
- Extend Glossary
- Finish containerization / Docker Swarm for eventual deployment

This is just from the top of my head, let me know if something jumps out that you'd love to tackle or if you have something else you think is high priority!

**Comment by supernoir** [comment]
I have been spending so much time with this stupid Rest Hooks lib that I really like but for some reason can't get to run properly lol!!
